### ISSUE TITLE
"slow_conv2d_cpu" not implemented for 'Half'

### ISSUE THREAD

**Issue by 0x32-l3git** [RootKit-Org/AI-Aimbot#114]
Traceback (most recent call last):
  File "C:\Users\kidsa\Desktop\AI-Aimbot-main\main.py", line 250, in <module>
    main()
  File "C:\Users\kidsa\Desktop\AI-Aimbot-main\main.py", line 152, in main
    results = model(im, size=screenShotHeight)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kidsa\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kidsa\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kidsa/.cache\torch\hub\ultralytics_yolov5_master\models\common.py", line 688, in forward
    return self.model(ims.to(p.device).type_as(p), augment=augment)  # inference
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kidsa\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kidsa/.cache\torch\hub\ultralytics_yolov5_master\models\common.py", line 527, in forward
    y = self.model(im, augment=augment, visualize=visualize) if augment or visualize else self.model(im)
                                                                                          ^^^^^^^^^^^^^^
  File "C:\Users\kidsa\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kidsa/.cache\torch\hub\ultralytics_yolov5_master\models\yolo.py", line 209, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kidsa/.cache\torch\hub\ultralytics_yolov5_master\models\yolo.py", line 121, in _forward_once
    x = m(x)  # run
        ^^^^
  File "C:\Users\kidsa\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kidsa/.cache\torch\hub\ultralytics_yolov5_master\models\common.py", line 71, in forward_fuse
    return self.act(self.conv(x))
                    ^^^^^^^^^^^^
  File "C:\Users\kidsa\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kidsa\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kidsa\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'
"slow_conv2d_cpu" not implemented for 'Half'

**Comment by 0x32-l3git** [comment]
wtf

**Comment by uc-grringo** [comment]
Same here...

**Comment by natbuki** [comment]
its just cause your running off of cpu you might have to use a different way to use the aimbot
