### ISSUE TITLE
Error Code 4: Internal Error (Engine deserialization failed.)

### ISSUE THREAD

**Issue by qq529879477** [RootKit-Org/AI-Aimbot#21]
Loading yolov5s320Half.engine for TensorRT inference...
[08/02/2022-00:09:49] [TRT] [I] [MemUsageChange] Init CUDA: CPU +412, GPU +0, now: CPU 12438, GPU 1245 (MiB)
[08/02/2022-00:09:49] [TRT] [I] Loaded engine size: 15 MiB
[08/02/2022-00:09:49] [TRT] [E] 6: The engine plan file is generated on an incompatible device, expecting compute 8.6 got compute 7.5, please rebuild.
[08/02/2022-00:09:49] [TRT] [E] 4: [runtime.cpp::nvinfer1::Runtime::deserializeCudaEngine::50] Error Code 4: Internal Error (Engine deserialization failed.)
Traceback (most recent call last):
  File "C:\ai\main_tensorrt_gpu.py", line 187, in <module>
    main()
  File "C:\ai\main_tensorrt_gpu.py", line 83, in main
    model = DetectMultiBackend('yolov5s320Half.engine', device=torch.device('cuda'), dnn=False, data='', fp16=True)
  File "C:\ai\models\common.py", line 389, in __init__
    for index in range(model.num_bindings):
AttributeError: 'NoneType' object has no attribute 'num_bindings'

**Comment by JiaqinKang** [comment]
What do you mean this has no content, This is the error code I received with tensorrt.

**Comment by Qfc9** [comment]
Doing what? Vanilla code? What versions of tookit are you using? What version of cuDNN? What version of Tensorrt?

This is an internal error to tensorrt, not our code. So it could be a bunch of different issues. The error says you are missing num_bindings, why are they missing? Can't answer that unless I know the prior content. You posting an error is extremely vague. 

Additionally, tensorrt version is for ML pros only since it can be pretty cancer to work with. 

If you want more personal help, you can join our discord.

**Comment by JiaqinKang** [comment]
There's no need to be so aggressive, I have already joined the discord but
no one offered any helps. if you require more information, you can kindly
ask me to provide more details. There's no need to be a ass. Was I being
rude first? wtf.
