### ISSUE TITLE
Overload resolution failed

### ISSUE THREAD

**Issue by LazyC-99** [RootKit-Org/AI-Aimbot#22]
Loading yolov5s320Half.engine for TensorRT inference...
[08/09/2022-18:25:17] [TRT] [I] [MemUsageChange] Init CUDA: CPU +292, GPU +0, now: CPU 7334, GPU 990 (MiB)
[08/09/2022-18:25:17] [TRT] [I] Loaded engine size: 31 MiB
[08/09/2022-18:25:17] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in engine deserialization: CPU +0, GPU +30, now: CPU 0, GPU 30 (MiB)
[08/09/2022-18:25:17] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +8, now: CPU 0, GPU 38 (MiB)
Traceback (most recent call last):
  File "D:\Game\Ai-Aimbot-yolov5\main_tensorrt_gpu.py", line 187, in <module>
    main()
  File "D:\Game\Ai-Aimbot-yolov5\main_tensorrt_gpu.py", line 162, in main
    cv2.rectangle(npImg, (startX, startY), (endX, endY),
cv2.error: OpenCV(4.6.0) :-1: error: (-5:Bad argument) in function 'rectangle'
> Overload resolution failed:
>  - img is not a numpy array, neither a scalar
>  - Expected Ptr<cv::UMat> for argument 'img'
>  - img is not a numpy array, neither a scalar
>  - Expected Ptr<cv::UMat> for argument 'img'

**Comment by Qfc9** [comment]
This has no content
