### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 11-ovo-11** [RootKit-Org/AI-Aimbot#273]
Thank you for sharing first.
I chose the fast version,on my laptop,and then it occurred to me:
(-21414, -21480, -21094, -21160)
Traceback (most recent call last):
  File "D:\AI-Aimbot-3.1.0\main.py", line 168, in <module>
    main()
  File "D:\AI-Aimbot-3.1.0\main.py", line 19, in main
    camera, cWidth, cHeight = gameSelection.gameSelection()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI-Aimbot-3.1.0\gameSelection.py", line 72, in gameSelection
    camera = bettercam.create(region=region, output_color="BGRA", max_buffer_len=512)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\bettercam\__init__.py", line 115, in create
    return __factory.create(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\bettercam\__init__.py", line 72, in create
    camera = BetterCam(
             ^^^^^^^^^^
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\bettercam\bettercam.py", line 50, in __init__
    self._validate_region(self.region)
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\bettercam\bettercam.py", line 238, in _validate_region
    raise ValueError(
ValueError: Invalid Region: Region should be in 1493x933
Invalid Region: Region should be in 1493x933
Ask @Wonder for help in our Discord in the #ai-aimbot channel ONLY: https://discord.gg/rootkitorg 
Exception ignored in: <function BetterCam.__del__ at 0x000001A8E4D10220>
Traceback (most recent call last):
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\bettercam\bettercam.py", line 248, in __del__
    self.release()
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\bettercam\bettercam.py", line 243, in release
    self.stop()
  File "C:\Users\86180\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\bettercam\bettercam.py", line 143, in stop
    if self.is_capturing:
       ^^^^^^^^^^^^^^^^^
AttributeError: 'BetterCam' object has no attribute 'is_capturing'
I don't know if my webcam is broken or if there's something wrong with my programming environment. So, I would like to learn if anyone has encountered the same problem and how did you solve it?

**Comment by 11-ovo-11** [comment]
I have now resolved the issue. I needed to adjust the in-game settings from fullscreen to windowed mode, and then the program was able to run. However, I have another problem.
Please enter the number corresponding to the window you'd like to select: 7
Successfully activated the game window...
(960, 523, 1280, 843)
Downloading: "https://github.com/ultralytics/yolov5/zipball/master&#34;  to C:\Users\86180/.cache\torch\hub\master.zip
YOLOv5  2023-11-27 Python-3.12.0 torch-2.5.1+cpu CPU

Fusing layers...
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients, 16.4 GFLOPs
Adding AutoShape...
C:\Users\86180/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:865: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with amp.autocast(autocast):
CPS: 1

**Comment by 11-ovo-11** [comment]
> I have now resolved the issue. I needed to adjust the in-game settings from fullscreen to windowed mode, and then the program was able to run. However, I have another problem. Please enter the number corresponding to the window you'd like to select: 7 Successfully activated the game window... (960, 523, 1280, 843) Downloading: "https://github.com/ultralytics/yolov5/zipball/master&#34; to C:\Users\86180/.cache\torch\hub\master.zip YOLOv5 2023-11-27 Python-3.12.0 torch-2.5.1+cpu CPU
> 
> Fusing layers... YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients, 16.4 GFLOPs Adding AutoShape... C:\Users\86180/.cache\torch\hub\ultralytics_yolov5_master\models\common.py:865: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead. with amp.autocast(autocast): CPS: 1


However, when I modified the content and reran it, I found that common.py reverted back to its previous state.
