### ISSUE TITLE
I encountered some problems with dxcam when starting the project

### ISSUE THREAD

**Issue by kerryethu** [RootKit-Org/AI-Aimbot#29]
Traceback (most recent call last):
  File "main.py", line 201, in <module>
    main()
  File "main.py", line 72, in main
    camera = dxcam.create(region=region)
  File "F:\conda\envs\yolo2\lib\site-packages\dxcam\__init__.py", line 110, in create
    return __factory.create(
  File "F:\conda\envs\yolo2\lib\site-packages\dxcam\__init__.py", line 70, in create
    camera = DXCamera(
  File "F:\conda\envs\yolo2\lib\site-packages\dxcam\dxcam.py", line 33, in __init__
    self._duplicator: Duplicator = Duplicator(
  File "<string>", line 6, in __init__
  File "F:\conda\envs\yolo2\lib\site-packages\dxcam\core\duplicator.py", line 19, in __post_init__
    output.output.DuplicateOutput(device.device, ctypes.byref(self.duplicator))
_ctypes.COMError: (-2005270524, '指定的设备接口或功能级别在此系统上不受支持。', (None, None, None, 0, None))
Exception ignored in: <function DXCamera.__del__ at 0x000001EA142683A0>
Traceback (most recent call last):
  File "F:\conda\envs\yolo2\lib\site-packages\dxcam\dxcam.py", line 243, in __del__
    self.release()
  File "F:\conda\envs\yolo2\lib\site-packages\dxcam\dxcam.py", line 238, in release
    self.stop()
  File "F:\conda\envs\yolo2\lib\site-packages\dxcam\dxcam.py", line 138, in stop
    if self.is_capturing:
AttributeError: 'DXCamera' object has no attribute 'is_capturing'

I'm a novice from China, just started learning this project, requesting detailed pointers
Thank you very much

**Comment by Apathy929** [comment]
I'm in the same situation as you.

**Comment by Qfc9** [comment]
Umm I think the fix for that is just to rerun it acouple times till it works. Ill keep my eye open for the solultion

**Comment by blackzhangwei** [comment]
I'm in the same situation as you.i try to find solution

**Comment by TonttuHomo** [comment]
Just click the window you want to capture before it says that, easy fix.

**Comment by Hyphonic** [comment]
^Doesnt work

**Comment by iceeburr** [comment]
Has anyone found a solution? If you did reply here or contact me on Discord - iceeburr#0746. Thanks!

**Comment by DDGay** [comment]
Same problem was solved by this https://github.com/SerpentAI/D3DShot/issues/27

**Comment by SKRecreated** [comment]
Another soloution that may work is making it windowed fullscreen/fullscreen windowed or windows

**Comment by Alexandros444** [comment]
> Another solution is to modify code `cam = dxcam.create(device_idx=0, output_idx=0)` Change device_idx and output_idx values (0, 1, 2, ...) Your device info can be saw by:
> 
> ```
> dxcam.device_info()
> dxcam.output_info()
> ```

Does not change anything for me, there is only one Device[0] available.
