### ISSUE TITLE
ModuleNotFoundError: No module named 'bettercam'

### ISSUE THREAD

**Issue by mirmr214** [RootKit-Org/AI-Aimbot#290]
(Neural Network Aimbot)
Traceback (most recent call last):
  File "C:\Users\WDAGUtilityAccount\Desktop\FortniteV1.7\FortniteV1.7\FortniteV1.7\V1.7 Rofus\lunar.py", line 75, in <module>
    from lib.aimbot import Aimbot
  File "C:\Users\WDAGUtilityAccount\Desktop\FortniteV1.7\FortniteV1.7\FortniteV1.7\V1.7 Rofus\lib\aimbot.py", line 12, in <module>
    import bettercam
ModuleNotFoundError: No module named 'bettercam'

Anyone know how to fix?

**Comment by is7706** [comment]
pip install bettercam
