### ISSUE TITLE
Hi i have some problems 

### ISSUE THREAD

**Issue by Hiradpi** [RootKit-Org/AI-Aimbot#36]
C:\Users\Hirad\Desktop\unfx-proxy-checker-master\AI-Aimbot-main>python main.py
Traceback (most recent call last):
  File "C:\Users\Hirad\Desktop\unfx-proxy-checker-master\AI-Aimbot-main\main.py", line 211, in <module>
    main()
  File "C:\Users\Hirad\Desktop\unfx-proxy-checker-master\AI-Aimbot-main\main.py", line 75, in main
    camera = dxcam.create(region=region)
  File "C:\Users\Hirad\AppData\Local\Programs\Python\Python310\lib\site-packages\dxcam\__init__.py", line 112, in create
    return __factory.create(
  File "C:\Users\Hirad\AppData\Local\Programs\Python\Python310\lib\site-packages\dxcam\__init__.py", line 71, in create
    camera = DXCamera(
  File "C:\Users\Hirad\AppData\Local\Programs\Python\Python310\lib\site-packages\dxcam\dxcam.py", line 46, in __init__
    self._validate_region(self.region)
  File "C:\Users\Hirad\AppData\Local\Programs\Python\Python310\lib\site-packages\dxcam\dxcam.py", line 233, in _validate_region
    raise ValueError(
ValueError: Invalid Region: Region should be in 1920x1080
Exception ignored in: <function DXCamera.__del__ at 0x000002A71F999BD0>
Traceback (most recent call last):
  File "C:\Users\Hirad\AppData\Local\Programs\Python\Python310\lib\site-packages\dxcam\dxcam.py", line 243, in __del__
    self.release()
  File "C:\Users\Hirad\AppData\Local\Programs\Python\Python310\lib\site-packages\dxcam\dxcam.py", line 238, in release
    self.stop()
  File "C:\Users\Hirad\AppData\Local\Programs\Python\Python310\lib\site-packages\dxcam\dxcam.py", line 138, in stop
    if self.is_capturing:
AttributeError: 'DXCamera' object has no attribute 'is_capturing'

**Comment by Xehia** [comment]
Me too, i've already set the region at 1920x1080 (my screen size), but it still doesn't work

**Comment by ZCban** [comment]
I think the Windows u selct on script not Active in background

**Comment by Xehia** [comment]
Yeah, you should open your window just after the script started, for me it worked.

**Comment by iceeburr** [comment]
Has anyone found a solution? If you did reply here or contact me on Discord - iceeburr#0746. Thanks!
