### ISSUE TITLE
error and traceback

### ISSUE THREAD

**Issue by roma777roma** [RootKit-Org/AI-Aimbot#53]
Please read the below message and think about how it could be solved before posting it on discord.
Traceback (most recent call last):
  File "C:\Users\aib\Downloads\AI-Aimbot-main\main.py", line 223, in <module>
    main()
  File "C:\Users\aib\Downloads\AI-Aimbot-main\main.py", line 80, in main
    camera = dxcam.create(region=region)
  File "C:\Users\aib\AppData\Local\Programs\Python\Python39\lib\site-packages\dxcam\__init__.py", line 112, in create
    return __factory.create(
  File "C:\Users\aib\AppData\Local\Programs\Python\Python39\lib\site-packages\dxcam\__init__.py", line 71, in create
    camera = DXCamera(
  File "C:\Users\aib\AppData\Local\Programs\Python\Python39\lib\site-packages\dxcam\dxcam.py", line 46, in __init__
    self._validate_region(self.region)
  File "C:\Users\aib\AppData\Local\Programs\Python\Python39\lib\site-packages\dxcam\dxcam.py", line 233, in _validate_region
    raise ValueError(
ValueError: Invalid Region: Region should be in 1920x1080

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\aib\Downloads\AI-Aimbot-main\main.py", line 227, in <module>
    traceback.print_exception(e)
TypeError: print_exception() missing 2 required positional arguments: 'value' and 'tb'
Exception ignored in: <function DXCamera.__del__ at 0x000001CBE5959310>
Traceback (most recent call last):
  File "C:\Users\aib\AppData\Local\Programs\Python\Python39\lib\site-packages\dxcam\dxcam.py", line 243, in __del__
    self.release()
  File "C:\Users\aib\AppData\Local\Programs\Python\Python39\lib\site-packages\dxcam\dxcam.py", line 238, in release
    self.stop()
  File "C:\Users\aib\AppData\Local\Programs\Python\Python39\lib\site-packages\dxcam\dxcam.py", line 138, in stop
    if self.is_capturing:
AttributeError: 'DXCamera' object has no attribute 'is_capturing'

**Comment by miroet** [comment]
i have that toooooooooooooooooooo

**Comment by Qfc9** [comment]
Check discord
