### ISSUE TITLE
Visuals error

### ISSUE THREAD

**Issue by Iauygbagi** [RootKit-Org/AI-Aimbot#71]
Traceback (most recent call last):
File "C:\Users\Muzi\Desktop\AI-Aimbot-main\main_onnx_cpu.py", line 210, in <module>
main()
File "c:\Users\Muzi\Desktop\AI-Aimbot-main\main_onnx_cpu.py", line 201, in main
cv2.imshow('Live Feed',npImg)
File "C:\Users\Muzi\Desktop\AI-Aimbot-main\utils\general.py", line 1135, in imshow
imshow_(path.encode('unicode_escape').decode(),im)
cv2.error: OpenCV(4.7.0): -1: error: (-5:Bad argument) in function 'imshow>Overload resolution failed:
- mat data type = 23 is not supported
- Expected Ptr<cv::cuda::GpuMat> for argument'mat 
- Expected Ptr<cv::UMat> for argument'mat'

OpenCV(4.7.0): -1: error: (-5:Bad argument) in function 'imshow>
   overload resolution failed:
- mat data type = 23 is not supported
- Expected Ptr<cv::cuda::GpuMat> for argument 'mat’
- Expected Ptr<cv::UMat> for argument ‘may ’

I get the above error when setting visuals to True in main_onnx_cpu.py 
Pls help
Thank you

**Comment by Qfc9** [comment]
Fixed that with the latest update
