### ISSUE TITLE
Error after selecting window

### ISSUE THREAD

**Issue by icedbug** [RootKit-Org/AI-Aimbot#82]
Traceback (most recent call last):
  File "C:\Users\jacob\Downloads\AI-Aimbot-main\AI-Aimbot-main\main_onnx_nvidia.py", line 244, in <module>
    main()
  File "C:\Users\jacob\Downloads\AI-Aimbot-main\AI-Aimbot-main\main_onnx_nvidia.py", line 126, in main
    ort_sess = ort.InferenceSession('yolov5s320.onnx', sess_options=so, providers=[
  File "C:\Users\jacob\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 360, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\jacob\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 397, in _create_inference_session    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from yolov5s320.onnx failed:Load model yolov5s320.onnx failed. File doesn't exist
[ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from yolov5s320.onnx failed:Load model yolov5s320.onnx failed. File doesn't exist

Fisrt I had problems with Cupy but solved it. But now after I selecting the right window, this happen......... I have no clue how to fix this. 

Anyone have some tips??

Thank you in advance!

**Comment by icedbug** [comment]
running main_onnx_nvidia.py. With latest Cuda 12

**Comment by icedbug** [comment]
Solved. I reinstalled a libbery
