### ISSUE TITLE
Aimbot Error (slow_conv2d_cpu not implemented)

### ISSUE THREAD

**Issue by SKRecreated** [RootKit-Org/AI-Aimbot#87]
Before I was getting an error that I didn't have cuda and I tried to install it while using the nvidia onmx but then it didnt work so I tried using the main.py. I got errors and I fixed it by activiting power saving mode for python and setting it to borderless fullscreen. Now I'm getting this: RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'
"slow_conv2d_cpu" not implemented for 'Half'

(error message starts here)
Please enter the number corresponding to the window you'd like to select: 8
Successfully activated the game window...
Downloading: "https://github.com/ultralytics/yolov5/zipball/master" to C:\Users\JakePC/.cache\torch\hub\master.zip
YOLOv5  2023-4-6 Python-3.10.5 torch-2.0.0+cpu CPU

Fusing layers...
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients
Adding AutoShape...
Please read the below message and think about how it could be solved before posting it on discord.
Traceback (most recent call last):
  File "C:\Users\JakePC\Desktop\Stuff\bingchilling\bing chillin\main.py", line 250, in <module>
    main()
  File "C:\Users\JakePC\Desktop\Stuff\bingchilling\bing chillin\main.py", line 152, in main
    results = model(im, size=screenShotHeight)
  File "C:\Users\JakePC\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\JakePC\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\JakePC/.cache\torch\hub\ultralytics_yolov5_master\models\common.py", line 675, in forward
    return self.model(ims.to(p.device).type_as(p), augment=augment)  # inference
  File "C:\Users\JakePC\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\JakePC/.cache\torch\hub\ultralytics_yolov5_master\models\common.py", line 514, in forward
    y = self.model(im, augment=augment, visualize=visualize) if augment or visualize else self.model(im)
  File "C:\Users\JakePC\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\JakePC/.cache\torch\hub\ultralytics_yolov5_master\models\yolo.py", line 209, in forward
    return self._forward_once(x, profile, visualize)  # single-scale inference, train
  File "C:\Users\JakePC/.cache\torch\hub\ultralytics_yolov5_master\models\yolo.py", line 121, in _forward_once
    x = m(x)  # run
  File "C:\Users\JakePC\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\JakePC/.cache\torch\hub\ultralytics_yolov5_master\models\common.py", line 59, in forward_fuse
    return self.act(self.conv(x))
  File "C:\Users\JakePC\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\JakePC\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\JakePC\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'
"slow_conv2d_cpu" not implemented for 'Half'
Please read the above message and think about how it could be solved before posting it on discord.

**Comment by ArinLP** [comment]
I have the exact same problem and I don't know what to do about it

**Comment by NULL204** [comment]
你的CUDA版本和Pytorch版本不符合，pytorch无法使用
