### ISSUE TITLE
Dxcam problem

### ISSUE THREAD

**Issue by Gibroooooo** [RootKit-Org/AI-Aimbot#93]
Traceback (most recent call last):
File "A:\Downloads\AI-Aimbot-main\main.py", line 250, in
main()
File "A:\Downloads\AI-Aimbot-main\main.py", line 108, in main
camera = dxcam.create(region=region)
File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\site-packages\dxcam_init_.py", line 112, in create
return _factory.create(
File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\site-packages\dxcam_init.py", line 71, in create
camera = DXCamera(
File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\site-packages\dxcam\dxcam.py", line 33, in init
self._duplicator: Duplicator = Duplicator(
File "", line 6, in init
File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\site-packages\dxcam\core\duplicator.py", line 19, in post_init
output.output.DuplicateOutput(device.device, ctypes.byref(self.duplicator))
_ctypes.COMError: (-2005270524, '指定的设备接口或功能级别在此系统上不受支持。', (None, None, None, 0, None))
(-2005270524, '指定的设备接口或功能级别在此系统上不受支持。', (None, None, None, 0, None))
Please read the above message and think about how it could be solved before posting it on discord.
Exception ignored in: <function DXCamera.del at 0x000002669F22C040>
Traceback (most recent call last):
File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\site-packages\dxcam\dxcam.py", line 243, in del
self.release()
File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\site-packages\dxcam\dxcam.py", line 238, in release
self.stop()
File "C:\Users\X\AppData\Local\Programs\Python\Python310\lib\site-packages\dxcam\dxcam.py", line 138, in stop
if self.is_capturing:
AttributeError: 'DXCamera' object has no attribute 'is_capturing'

**Comment by Villageslayer** [comment]
your python version needs to be 3.8/3.9 with 3.8 Recomended.  Install 3.8 and Try again

**Comment by NULL204** [comment]
It doesn't work, I use 3.8.10, still reporting an error
